services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - db
    restart: always

networks:
  db:
    driver: bridge

volumes:
  db:
