spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/assistant
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  messages:
    encoding: UTF-8
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            port: ${SMTP_PORT}
            class: ${SOCKETFACTORY_CLASS}

auth:
  jwt:
    expirationDays: 30
    secret: ${USER_SECRET}
    issuer: enterprise-assistant-service

email:
  sender:
    from: ${MAIL_USERNAME}
    subject: ${MAIL_SUBJECT}
